// This file gets all api values and simulate them with out using any other tools.
// You can also make pos requests


GET http://hulunfechi.ethioscholarship.com/api/hulunfechi/getAllEventCategory/

###

GET http://hulunfechi.ethioscholarship.com/api/hulunfechi/getAllEvent/1/1

###

GET http://hulunfechi.ethioscholarship.com/api/hulunfechi/getTodayEvent/10/1
###

GET http://hulunfechi.ethioscholarship.com/api/hulunfechi/getNewEvent/10/1
###

GET http://hulunfechi.ethioscholarship.com/api/hulunfechi/getUpcomingEvent/10/1
###

GET http://hulunfechi.ethioscholarship.com/api/hulunfechi/getNewEvent/1/1

###

GET http://hulunfechi.ethioscholarship.com/api/hulunfechi/getAllUser

###
GET http://hulunfechi.ethioscholarship.com/api/hulunfechi/showEventType/1

###
GET http://hulunfechi.ethioscholarship.com/api/hulunfechi/searchEvent/hi/10/1

###

###
GET http://hulunfechi.ethioscholarship.com/api/hulunfechi/searchEventByCategory/2/10/1

###
GET  https://apiv2.hulunfechi.com/api/posts
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJkdWthQGFkbWluLmNvbSIsImlhdCI6MTY0Mjg1NDUzNSwiZXhwIjoxNjQyOTQwOTM1fQ.nvTK9GNb1mmGXZgA8H8xuubSIWdXzfZWVbuYVRPneV3EBYV9sqeaG_Yzdum8K1orR1vbNFrNb6M6rmjic6N9xg
Accept: application/json

###
GET  https://apiv2.hulunfechi.com/api/categories
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0ZXN0QGFkbWluLmNvbSIsImlhdCI6MTY0MjQzMzY0MiwiZXhwIjoxNjQyNTIwMDQyfQ.S_QNLrTXUiSc1f3_9-jgoPydtSH7sG0wJIvPIYORxxHXfFykEi-9-W7ItZcsujik6ZiqbeNKuSwR80GfgcXtPQ
Accept: application/json
sectors
###

GET  https://apiv2.hulunfechi.com/api/posts/139/comments
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0ZXN0QGFkbWluLmNvbSIsImlhdCI6MTY0MjY5Nzc5OSwiZXhwIjoxNjQyNzg0MTk5fQ.fXihom_Q_Nyqgz-6SCjVWGd1Y5vihkHUoKPtYEtrZoaJ7tWVXxO3PlYhznw-tzr5esPzOJEyC2r63NeGcevokQ
Accept: application/json

###
GET  https://apiv2.hulunfechi.com/api/posts
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIyMDIyQGFkbWluLmNvbSIsImlhdCI6MTY0MzgxNjc0MSwiZXhwIjoxNjQzOTAzMTQxfQ.BxomSsvD3SQlqC3ai1yD1nTTukhEU_MWTa9_8cpHBMk9ViU0lf0UtMzJPwdyu-qDK9btUXV9ngt7rd6HGZ1vxg
Accept: application/json

###
POST https://apiv2.hulunfechi.com/api/auth/signin
content-type: application/json
Accept: application/json

{
    "username": "duka@admin.com",
    "password": "123456"
      
    }
###
POST https://apiv2.hulunfechi.com/api/posts/139/comments
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0ZXN0QGFkbWluLmNvbSIsImlhdCI6MTY0Mjc1MjgzMiwiZXhwIjoxNjQyODM5MjMyfQ.tB1ZBdIW_AOBuqQ9UTdEoH43ClolhKNdMzmlDO1n9rb65qAOWHWxrpc3EAvh8pSw4sv36g7JuvpeGQfXcDk2CA
Accept: application/json

{
"comment":"Buki",
"user":{"id":33},
"dateAdded":"2022-01-21"
}
###
PUT https://apiv2.hulunfechi.com/api/auth/user/3
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIyMDIyQGFkbWluLmNvbSIsImlhdCI6MTY0MzgxNjc0MSwiZXhwIjoxNjQzOTAzMTQxfQ.BxomSsvD3SQlqC3ai1yD1nTTukhEU_MWTa9_8cpHBMk9ViU0lf0UtMzJPwdyu-qDK9btUXV9ngt7rd6HGZ1vxg
Accept: application/json

{

    "username": "duka@admin.com", 
     "fullname": null,
      "firstname": "Eshetu",
       "lastname": "Lukas",
        "email": "duka@admin.com",
         "country": "Ethiopiaaaa", 
         "phone": "0916740322",
          "profession": "Software",
           "dob": null,
            "region": "Addis Ababa", 
            "city": "Addis ababa",
             "woreda": null,
              "subcity": null, 
              "housenumber": null, 
              "state": null, 
              "street": null, 
              "ssn": 1234567, 
              "account": 1222,
               "bank": "CBE",
                "tin": 1234567555, 
                "usercountry": [], "following": [{"id": 1}, {"id": 7}], 
                "usercategories": [{"id": 7}],
                 "role": ["user"]
                 
                 }
    
###

POST https://apiv2.hulunfechi.com/api/posts
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIyMDIyQGFkbWluLmNvbSIsImlhdCI6MTY0MzgxNjc0MSwiZXhwIjoxNjQzOTAzMTQxfQ.BxomSsvD3SQlqC3ai1yD1nTTukhEU_MWTa9_8cpHBMk9ViU0lf0UtMzJPwdyu-qDK9btUXV9ngt7rd6HGZ1vxg
Accept: application/json

{
        "title": "The Truth About the Jesus of the Bible",
        "description": "If we look at the Gospels, however, a totally different picture emerges. Here is no “gentle Jesus meek and mild,” but a person so dynamic and so inspiring that hard-bitten ﬁshermen, tough tax collectors, Roman soldiers, and a man with one of the greatest intellects of his day—the apostle Paul—were all prepared to put their reputations and their lives on the line in order to follow Him.",
        "published": false,
        "likes": 10,
        "shares": 6,
        "sectors": {
            "id":1
        },
        "expiry": "2022-03-20",
        "user": {
            "id": 3

        },
        "category": {
            "id": 1

        },
        "platform": {
            "id": 1
        },
        "country": {
            "id": 1
        },
        "subategory": {
            "id": 1
       
    }
    }
    
###
POST https://apiv2-dev.hulunfechi.com/api/auth/signup
content-type: application/json
Accept: application/json

{
    "username": "2022@admin.com",
    "password": "123456",
    "role": ["user"],
    "email": "2022@admin.com",
    "firstname": "Eshetu",
    "lastname": "Lukas",
    "gender":"Male",
    "phone":"0916740322"
     
}
###

POST https://apiv2.hulunfechi.com/api/country
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0ZXN0QGFkbWluLmNvbSIsImlhdCI6MTY0Mjc1MjgzMiwiZXhwIjoxNjQyODM5MjMyfQ.tB1ZBdIW_AOBuqQ9UTdEoH43ClolhKNdMzmlDO1n9rb65qAOWHWxrpc3EAvh8pSw4sv36g7JuvpeGQfXcDk2CA
Accept: application/json

{
    
    "name": "Ethiopia",
    "description": "descriptions"
  
}
###
Get https://apiv2.hulunfechi.com/api/categories
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0ZXN0QGFkbWluLmNvbSIsImlhdCI6MTY0Mjc1MjgzMiwiZXhwIjoxNjQyODM5MjMyfQ.tB1ZBdIW_AOBuqQ9UTdEoH43ClolhKNdMzmlDO1n9rb65qAOWHWxrpc3EAvh8pSw4sv36g7JuvpeGQfXcDk2CA
Accept: application/json

###
POST https://apiv2.hulunfechi.com/api/platform
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0ZXN0QGFkbWluLmNvbSIsImlhdCI6MTY0Mjc1MjgzMiwiZXhwIjoxNjQyODM5MjMyfQ.tB1ZBdIW_AOBuqQ9UTdEoH43ClolhKNdMzmlDO1n9rb65qAOWHWxrpc3EAvh8pSw4sv36g7JuvpeGQfXcDk2CA
Accept: application/json

{
    "name": "Wetatoch",
    "description": "descriptions",
    "sectors":{"id":3}

}
###


POST https://apiv2.hulunfechi.com/api/subcategory
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0ZXN0QGFkbWluLmNvbSIsImlhdCI6MTY0Mjc1MjgzMiwiZXhwIjoxNjQyODM5MjMyfQ.tB1ZBdIW_AOBuqQ9UTdEoH43ClolhKNdMzmlDO1n9rb65qAOWHWxrpc3EAvh8pSw4sv36g7JuvpeGQfXcDk2CA
Accept: application/json

{
    "name": "Education",
    "description": "descriptions",
    "category":{
        "id":1
    },
    "sectors": {
        "id":3
    },
        "platform": {
        "id":1
    }
}

###




POST http://localhost:5001/poly-market-jester/us-central1/order_status-default  /hulunfechi/createUser
content-type: application/json
Authorization: token eyJhbGciOiJSUzI1NiIsImtpZCI6IjdiODcxMTIzNzU0MjdkNjU3ZjVlMjVjYTAxZDU2NWU1OTJhMjMxZGIiLCJ0eXAiOiJKV1QifQ.eyJuYW1lIjoiRXNoZXR1IEx1a2FzIiwicGljdHVyZSI6Imh0dHBzOi8vbGgzLmdvb2dsZXVzZXJjb250ZW50LmNvbS9hLS9BT2gxNEdpQ2xBendRc0NXUlZiNno5Q1FBWTY3bFQ2STBMN0JuUEt2QWU4TXlBPXM5Ni1jIiwiaXNzIjoiaHR0cHM6Ly9zZWN1cmV0b2tlbi5nb29nbGUuY29tL3BvbHktbWFya2V0LWplc3RlciIsImF1ZCI6InBvbHktbWFya2V0LWplc3RlciIsImF1dGhfdGltZSI6MTYzMTYxMTc5NiwidXNlcl9pZCI6InZ5WVZEMzc1b25UWUJSN3FVeEsyTjE5QW9FeTEiLCJzdWIiOiJ2eVlWRDM3NW9uVFlCUjdxVXhLMk4xOUFvRXkxIiwiaWF0IjoxNjMzMDk0Njk2LCJleHAiOjE2MzMwOTgyOTYsImVtYWlsIjoidGVrYWx1a2FzQGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJmaXJlYmFzZSI6eyJpZGVudGl0aWVzIjp7Imdvb2dsZS5jb20iOlsiMTE0MTYwNjUyMDc2NDUyMTYwNTMwIl0sImVtYWlsIjpbInRla2
Accept: application/json

{
    "data":{
       "receiverPushToken": "eyJhbGciOiJSUzI1NiIsImtpZCI6IjdiODcxMTIzNzU0MjdkNjU3ZjVlMjVjYTAxZDU2NWU1OTJhMjMxZGIiLCJ0eXAiOiJKV1QifQ.eyJuYW1lIjoiRXNoZXR1IEx1a2FzIiwicGljdHVyZSI6Imh0dHBzOi8vbGgzLmdvb2dsZXVzZXJjb250ZW50LmNvbS9hLS9BT2gxNEdpQ2xBendRc0NXUlZiNno5Q1FBWTY3bFQ2STBMN0JuUEt2QWU4TXlBPXM5Ni1jIiwiaXNzIjoiaHR0cHM6Ly9zZWN1cmV0b2tlbi5nb29nbGUuY29tL3BvbHktbWFya2V0LWplc3RlciIsImF1ZCI6InBvbHktbWFya2V0LWplc3RlciIsImF1dGhfdGltZSI6MTYzMTYxMTc5NiwidXNlcl9pZCI6InZ5WVZEMzc1b25UWUJSN3FVeEsyTjE5QW9FeTEiLCJzdWIiOiJ2eVlWRDM3NW9uVFlCUjdxVXhLMk4xOUFvRXkxIiwiaWF0IjoxNjMzMDk0Njk2LCJleHAiOjE2MzMwOTgyOTYsImVtYWlsIjoidGVrYWx1a2FzQGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJmaXJlYmFzZSI6eyJpZGVudGl0aWVzIjp7Imdvb2dsZS5jb20iOlsiMTE0MTYwNjUyMDc2NDUyMTYwNTMwIl0sImVtYWlsIjpbInRla2FsdWthc0BnbW",
        "senderName": "Eshetu",
        "gigName": "Dance party",
        "updatedStatus": "REQUESTED",
        
    }
}



