import 'package:flutter/material.dart';

const Color kcPrimaryColor = Color(0xFF24ADB1);
const Color kcSecondaryColor = const Color(0xFF24ADB1);
const Color kcPrimaryColorDark = const Color(0xFF000000);
const Color kcBackgroundColor = const Color(0xFF1E4355);
const Color kcDarkGreyColor = const Color(0xFF1A1B1E);
const Color kcMediumGrey = const Color(0x1D8C8989);
const Color kcLightGrey = const Color(0xFFA4A9B8);
const Color kcMediumLightGrey = const Color(0xFF848B9E);
const Color kcVeryLightGrey = const Color(0xDDFFFFFF);
const Color kcLightGrey2 = const Color(0xFCFFFFFF);
const Color kcLightGrey3 = const Color(0xFFE7E5E5);
const Color kcLightGrey5 = const Color(0xFFE9E9E9);
const Color kcWhite = const Color(0xFFFFFFFF);
const Color kcLightBlue = const Color(0xFF4267B2);
const Color kcAppBackgroundColor = Color(0xFFF3F6FB);
const Color kcAppBackgroundColor2 = const Color(0xFF0A1824);
const Color kcItemsBackground = const Color(0xFF293f4e);
const Color kcLDeepGreen = const Color(0xFF09663E);
